"""Analyst coverage and billing, proxied from the services that own them.

Both routers are thin. Their job is to turn a service being unavailable into
something a page can render, rather than into a 500 that says nothing about
whether the rest of the platform is fine.

503 is used deliberately for that, with `Retry-After`. A 500 would suggest this
platform is broken; a 503 says a dependency is, which is both true and
actionable — the caller can show the rest of the page and try again.
"""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from pydantic import BaseModel, Field

from kairos.adapters.services.http import ServiceUnavailable
from kairos.core.tenancy.context import current_scope

router = APIRouter(tags=["market"])


def get_analyst():  # type: ignore[no-untyped-def]
    raise NotImplementedError("analyst client is not wired")


def get_billing():  # type: ignore[no-untyped-def]
    raise NotImplementedError("billing client is not wired")


# ---------------------------------------------------------------------------
# Wire shapes
# ---------------------------------------------------------------------------


class GradeResponse(BaseModel):
    firm: str
    from_grade: str
    to_grade: str
    action: str


class RatingResponse(BaseModel):
    symbol: str
    company_name: str
    consensus: str
    target_price: float | None
    target_high: float | None
    target_low: float | None
    analyst_count: int
    recent_grades: list[GradeResponse]
    updated_at: str | None
    upside: float | None = Field(
        default=None,
        description=(
            "Fraction between the given price and the consensus target. Null "
            "when either is missing — showing zero would assert fair value."
        ),
    )


class PlanResponse(BaseModel):
    id: int
    name: str
    price: str
    duration_days: int
    monthly_price: str


class PlanList(BaseModel):
    plans: list[PlanResponse]


class MembershipResponse(BaseModel):
    level: int
    active: bool
    expires_at: str | None


class RechargeRequest(BaseModel):
    plan_id: int
    request_id: Annotated[str, Field(min_length=1, max_length=64)] = Field(
        description=(
            "Idempotency key, generated by the client. A double-clicked buy "
            "must produce one order, which is only possible if both requests "
            "carry the same key."
        )
    )


class RechargeResponse(BaseModel):
    id: int
    plan_id: int
    amount: str
    state: str
    awaiting_payment: bool
    created_at: str | None
    paid_at: str | None


# ---------------------------------------------------------------------------
# Analyst
# ---------------------------------------------------------------------------


@router.get("/stocks/{symbol}/analyst", response_model=RatingResponse)
async def analyst_rating(
    symbol: str,
    price: Annotated[float | None, Query(gt=0)] = None,
    analyst=Depends(get_analyst),  # type: ignore[no-untyped-def]
) -> RatingResponse:
    """What the street thinks of a symbol.

    `price` is optional and only used to compute the upside. Taken as a
    parameter rather than fetched here because the caller is usually rendering
    a page that already has a live price, and fetching a second one would show
    two different numbers on the same screen.
    """
    try:
        rating = await analyst.rating(symbol)
    except ServiceUnavailable as unavailable:
        raise _degraded(unavailable) from unavailable

    if rating is None:
        # An uncovered symbol is not an error, but there is nothing to return.
        # 404 rather than an empty rating, because an empty rating rendered in
        # a card looks like coverage that says nothing.
        raise HTTPException(
            status.HTTP_404_NOT_FOUND, f"No analyst coverage for {symbol.upper()}"
        )

    return RatingResponse(
        symbol=rating.symbol,
        company_name=rating.company_name,
        consensus=rating.consensus,
        target_price=rating.target_price,
        target_high=rating.target_high,
        target_low=rating.target_low,
        analyst_count=rating.analyst_count,
        recent_grades=[
            GradeResponse(
                firm=g.firm, from_grade=g.from_grade, to_grade=g.to_grade, action=g.action
            )
            for g in rating.recent_grades
        ],
        updated_at=rating.updated_at.isoformat() if rating.updated_at else None,
        upside=rating.upside_from(price) if price else None,
    )


@router.get("/stocks/cache-stats")
async def analyst_cache_stats(
    analyst=Depends(get_analyst),  # type: ignore[no-untyped-def]
) -> dict[str, int]:
    """The analyst service's own cache counters.

    Exposed because a two-level cache whose hit rate nobody can see is a
    two-level cache nobody can tune.
    """
    try:
        return await analyst.cache_stats()
    except ServiceUnavailable as unavailable:
        raise _degraded(unavailable) from unavailable


# ---------------------------------------------------------------------------
# Billing
# ---------------------------------------------------------------------------


@router.get("/billing/plans", response_model=PlanList)
async def list_plans(
    billing=Depends(get_billing),  # type: ignore[no-untyped-def]
) -> PlanList:
    try:
        plans = await billing.plans()
    except ServiceUnavailable as unavailable:
        raise _degraded(unavailable) from unavailable

    return PlanList(
        plans=[
            PlanResponse(
                id=p.id,
                name=p.name,
                price=str(p.price),
                duration_days=p.duration_days,
                monthly_price=str(p.monthly_price),
            )
            for p in plans
        ]
    )


@router.get("/billing/membership", response_model=MembershipResponse)
async def membership(
    billing=Depends(get_billing),  # type: ignore[no-untyped-def]
) -> MembershipResponse:
    """The caller's own entitlement.

    The user is taken from the verified scope, never from a parameter. A user
    id a client could supply is a user id a client could change.
    """
    scope = current_scope()
    try:
        found = await billing.membership(str(scope.user_id))
    except ServiceUnavailable as unavailable:
        raise _degraded(unavailable) from unavailable

    return MembershipResponse(
        level=found.level,
        active=found.active,
        expires_at=found.expires_at.isoformat() if found.expires_at else None,
    )


@router.post(
    "/billing/recharge",
    status_code=status.HTTP_201_CREATED,
    response_model=RechargeResponse,
)
async def start_recharge(
    request: RechargeRequest,
    billing=Depends(get_billing),  # type: ignore[no-untyped-def]
) -> RechargeResponse:
    """Create an unpaid order.

    201 here, unlike an order proposal: the recharge service creates the row
    synchronously and hands back its id, so the thing described by the response
    genuinely exists by the time it arrives.
    """
    scope = current_scope()
    try:
        order = await billing.start_recharge(
            str(scope.user_id), request.plan_id, request_id=request.request_id
        )
    except ServiceUnavailable as unavailable:
        raise _degraded(unavailable) from unavailable

    return _recharge(order)


@router.get("/billing/recharge/{order_id}", response_model=RechargeResponse)
async def recharge_status(
    order_id: int,
    billing=Depends(get_billing),  # type: ignore[no-untyped-def]
) -> RechargeResponse:
    scope = current_scope()
    try:
        order = await billing.order(str(scope.user_id), order_id)
    except ServiceUnavailable as unavailable:
        raise _degraded(unavailable) from unavailable

    if order is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Order not found")
    return _recharge(order)


def _recharge(order) -> RechargeResponse:  # type: ignore[no-untyped-def]
    return RechargeResponse(
        id=order.id,
        plan_id=order.plan_id,
        amount=str(order.amount),
        state=order.state.name.lower(),
        awaiting_payment=order.awaiting_payment,
        created_at=order.created_at.isoformat() if order.created_at else None,
        paid_at=order.paid_at.isoformat() if order.paid_at else None,
    )


def _degraded(unavailable: ServiceUnavailable) -> HTTPException:
    """A dependency is down, and saying so is more useful than a 500.

    `Retry-After` is short because these outages are usually a restart rather
    than an incident, and a client that waits a minute to retry a service that
    came back in two seconds looks broken to the person watching it.
    """
    return HTTPException(
        status.HTTP_503_SERVICE_UNAVAILABLE,
        f"{unavailable.service} is unavailable",
        headers={"Retry-After": "5"},
    )


__all__ = ["Response", "router"]
