"""Membership and top-ups, from the recharge service.

That service owns the money: it creates the order, talks to the payment
gateway, holds the idempotency key, and closes an order that goes unpaid past
its deadline. This platform starts the flow and reads the outcome, and does not
model any of the states in between — a second copy of an order's status is a
second thing that can be wrong about whether someone paid.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import IntEnum

from kairos.adapters.services.http import ServiceCall


class OrderState(IntEnum):
    """The recharge service's status codes, named.

    Integers on the wire, because that is what it sends. Named here so that
    nothing downstream compares against a bare `2` and nobody has to remember
    which number means refunded.
    """

    UNPAID = 1
    PAID = 2
    CLOSED = 3
    REFUNDED = 4

    @property
    def settled(self) -> bool:
        """Nothing further will happen without someone asking for it."""
        return self in (OrderState.PAID, OrderState.CLOSED, OrderState.REFUNDED)


@dataclass(frozen=True, slots=True)
class Plan:
    """Something buyable."""

    id: int
    name: str
    price: Decimal
    duration_days: int

    @property
    def monthly_price(self) -> Decimal:
        """Comparable across plans of different lengths.

        A yearly plan and a monthly one are not otherwise comparable by their
        headline price, which is the number a reader sees first.
        """
        if self.duration_days <= 0:
            return self.price
        return (self.price / self.duration_days * 30).quantize(Decimal("0.01"))


@dataclass(frozen=True, slots=True)
class RechargeOrder:
    """A top-up, in whatever state the recharge service last had it."""

    id: int
    plan_id: int
    amount: Decimal
    state: OrderState
    created_at: datetime | None = None
    paid_at: datetime | None = None

    @property
    def awaiting_payment(self) -> bool:
        return self.state is OrderState.UNPAID


@dataclass(frozen=True, slots=True)
class Membership:
    """What a user is currently entitled to."""

    level: int
    expires_at: datetime | None = None

    @property
    def active(self) -> bool:
        """Level alone is not enough — an expired membership still has one."""
        if self.level <= 0:
            return False
        if self.expires_at is None:
            return True
        return self.expires_at > datetime.now(self.expires_at.tzinfo)


class BillingClient:
    """Starts a top-up and reads what became of it."""

    __slots__ = ("_call",)

    def __init__(self, call: ServiceCall) -> None:
        self._call = call

    async def plans(self) -> list[Plan]:
        body = await self._call.get("/recharge/plans")
        return [_plan(p) for p in _payload(body) or ()]

    async def membership(self, user_id: str) -> Membership:
        """The caller's entitlement.

        Absence is a real answer — most users have never bought anything — so
        it comes back as level zero rather than as None, and every caller is
        spared the same null check before asking whether it is active.
        """
        body = await self._call.get("/membership/me", headers=_acting_as(user_id))
        data = _payload(body)
        if not data:
            return Membership(level=0)
        return Membership(
            level=int(data.get("level") or 0),
            expires_at=_moment(data.get("expireTime")),
        )

    async def start_recharge(
        self, user_id: str, plan_id: int, *, request_id: str
    ) -> RechargeOrder:
        """Create an unpaid order.

        `request_id` is the idempotency key and is generated by the caller, not
        here. A user who double-clicks buy should end up with one order, and
        that is only possible if both requests carry the same key — which they
        cannot if the key is minted inside this call.
        """
        body = await self._call.post(
            "/recharge/order",
            {"planId": plan_id, "requestId": request_id},
            headers=_acting_as(user_id),
        )
        return _order(_payload(body) or {})

    async def order(self, user_id: str, order_id: int) -> RechargeOrder | None:
        body = await self._call.get_optional(
            f"/recharge/order/{order_id}", headers=_acting_as(user_id)
        )
        data = _payload(body)
        return None if not data else _order(data)


def _acting_as(user_id: str) -> dict[str, str]:
    """Who the call is for.

    The recharge service reads the user from its own token. This platform holds
    a session rather than that token, so it names the user explicitly — which
    is only safe because the header never crosses a trust boundary: it is set
    from the verified scope, never from anything a client sent.
    """
    return {"X-User-Id": user_id}


def _payload(body: object) -> dict | list | None:
    """Unwrap the service's envelope.

    It answers `{success, data, errorMsg}`. Reaching past that at every call
    site would mean every one of them independently deciding what to do when
    `success` is false.
    """
    if not isinstance(body, dict):
        return None

    # Checked before anything else. A refusal need not carry a `data` key at
    # all, and falling through to "no envelope, so this is the payload" would
    # hand back `{success, errorMsg}` as though it were the answer.
    if body.get("success") is False:
        return None

    if "data" not in body:
        # Not every endpoint wraps. One that returns its object directly is
        # taken at face value.
        return body

    data = body.get("data")
    return data if isinstance(data, (dict, list)) else None


def _plan(body: dict) -> Plan:
    return Plan(
        id=int(body.get("id") or 0),
        name=str(body.get("name") or ""),
        price=_money(body.get("price")),
        duration_days=int(body.get("durationDays") or 0),
    )


def _order(body: dict) -> RechargeOrder:
    raw_state = int(body.get("status") or OrderState.UNPAID)
    try:
        state = OrderState(raw_state)
    except ValueError:
        # A state this platform has not heard of is treated as unsettled rather
        # than guessed at. Showing it as paid on the strength of an unknown
        # number is the one mistake worth ruling out here.
        state = OrderState.UNPAID

    return RechargeOrder(
        id=int(body.get("id") or 0),
        plan_id=int(body.get("planId") or 0),
        amount=_money(body.get("amount")),
        state=state,
        created_at=_moment(body.get("createTime")),
        paid_at=_moment(body.get("payTime")),
    )


def _money(value: object) -> Decimal:
    """Money as Decimal, always.

    Through `str` even when the JSON gave a float, because `Decimal(0.1)` keeps
    the binary error and `Decimal("0.1")` does not.
    """
    if value is None:
        return Decimal(0)
    try:
        return Decimal(str(value))
    except (TypeError, ValueError, ArithmeticError):
        return Decimal(0)


def _moment(value: object) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(str(value))
    except ValueError:
        return None
